// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlunyzekwfctfhoojsuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsdW55emVrd2ZjdGZob29qc3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDgzMzQsImV4cCI6MjA2MjM4NDMzNH0.bt1dO8XcM1gAOWG5_c6mlzskVM1RkliFwcVAvSwsHJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);